<a href="https://colab.research.google.com/github/huanbv/BVU.CaoHoc.BuiVanHuan-XLA/blob/main/BVU_CaoHoc_BuiVanHuan_BT_ThaoLuan_Nhom1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
# Ma trận gốc
A = np.array([[0,1,2,3],
              [1,2,3,4],
              [2,3,4,5],
              [3,4,5,7]])

# --- Câu 1: Âm bản ---
A_N = 7 - A
print("Ma trận âm bản:\n", A_N)


Ma trận âm bản:
 [[7 6 5 4]
 [6 5 4 3]
 [5 4 3 2]
 [4 3 2 0]]


In [11]:

# --- Câu 4: Quay ảnh 90° ---
A_R = np.rot90(A, k=-1)  # quay 90 độ theo chiều kim đồng hồ
print("Ma trận quay 90°:\n", A_R)

Ma trận quay 90°:
 [[3 2 1 0]
 [4 3 2 1]
 [5 4 3 2]
 [7 5 4 3]]


In [12]:

# Ma trận gốc
A = np.array([[0,1,2,3],
              [1,2,3,4],
              [2,3,4,5],
              [3,4,5,7]])

# --- Câu 2: Histogram ---
hist, bins = np.histogram(A, bins=range(9))  # từ 0 đến 7
print("Histogram:", hist)


Histogram: [1 2 3 4 3 2 0 1]


In [13]:
# --- Câu 3: Phân ngưỡng ---
T = 4
A_T = np.where(A < T, 0, 7)
print("Ma trận phân ngưỡng:\n", A_T)

# Đếm số pixel vùng tối/sáng
dark_pixels = np.sum(A_T == 0)
bright_pixels = np.sum(A_T == 7)
print("Số pixel vùng tối:", dark_pixels)
print("Số pixel vùng sáng:", bright_pixels)

Ma trận phân ngưỡng:
 [[0 0 0 0]
 [0 0 0 7]
 [0 0 7 7]
 [0 7 7 7]]
Số pixel vùng tối: 10
Số pixel vùng sáng: 6
